# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

desc "Download certificates and provisioning profiles"
lane :download_certs do
  match(
    app_identifier: "com.dream.TravisTest",
    git_url: ENV['GIT_CERTS'],
    type: "development",
    readonly: true,
    )
end

desc "Create a Beta build"
lane :build_dev do
  gym(
  configuration: "Debug",
  export_method: "development",
  clean: true,
  silent: false,
  include_bitcode: false,
  )
end

desc "Submit to Hockey"
lane :submit_hockey do
  hockey(api_token: ENV['HOCKEY_TOKEN'])
  message = last_git_commit[:message]
  commit_hash = last_git_commit[:commit_hash]
  version = get_ipa_info_plist_value(key: "CFBundleShortVersionString")
  build_number = get_ipa_info_plist_value(key: "CFBundleVersion")
  slack(
    channel: "#ios_ci",
    slack_url: ENV['SLACK_URL'],
    default_payloads: [],
    payload: {
      'Commit Message' => message,
      'Commit Hash' => commit_hash,
      'Version' => "#{version} (#{build_number})",
      'Download'=> lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK],
    }
  )
end

desc "Build beta"
lane :beta do
  download_certs
  build_dev
  submit_hockey
end

end
