# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "test"
  lane :tests do
    run_tests(scheme: "TravisTest")
  end

  desc "download certs"
  lane :download_certs do
    match(
      app_identifier: "com.dream.TravisTest",
      git_url: "https://github.com/tuannme/TravisCert.git",
      type: "development",
      readonly: true,
    )
  end

  desc "get provisioning"
  lane :get_provisioning do
    sigh(
      app_identifier: "com.dream.TravisTest",
      development: true,
      readonly: true,
      username: "tuanhut92@gmail.com",
    )
  end

  desc "get certificates"
  lane :get_certs do
    cert(
      development: true,
      username: "tuanhut92@gmail.com",
    )
  end


  desc "Create a Beta build to Hockey"
  lane :build_dev_hockey do
    build_app(
      scheme: "TravisTest",
      workspace: "TravisTest.xcworkspace",
      export_method: "development",
      include_bitcode: false
    )
  end

  desc "Build beta"
  lane :beta do
    #get_certs
    #get_provisioning
    build_dev_hockey
  end

end
