# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
  end

  desc "Create a Beta build to Hockey"
    lane :build_dev_hockey do
      build_app(
        scheme: "TravisTest",
        workspace: "TravisTest.xcworkspace",
        export_method: "development",
        include_bitcode: false
      )
    end

  desc "Build beta"
    lane :beta do
      build_dev_hockey
    end

end
